version: "3.8"

name: cthree-discord-bot-production

services:
  database:
    image: postgres:17
    container_name: chtree-discord-bot-database
    networks:
      - cthree_discord_bot_network
    environment:
      POSTGRES_USER: cthree-bot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cthree-discord-bot
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    container_name: cthree-discord-bot-app
    networks:
      - cthree_discord_bot_network

volumes:
  postgres_data:

networks:
  - cthree_discord_bot_network:
