version: "3.8"

name: cthree-discord-bot-production

services:
  database:
    image: postgres:17
    container_name: cthree-discord-bot-database
    networks:
      - cthree_discord_bot_network
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: cthree-discord-bot-app
    networks:
      - cthree_discord_bot_network
    depends_on:
      - database
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  cthree_discord_bot_network:
    driver: bridge
