name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run formats
        run: npm run format

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy File to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.SSH_USERNAME }}/cthree-discord-bot"

      - name: Build and Run Bot
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/cthree-discord-bot

            echo "${{ secrets.ENV_FILE }}" | base64 -d > .env

            docker stop cthree-discord-bot || true
            docker rm cthree-discord-bot || true
            docker build -t cthree-discord-bot .
            docker run -d --name cthree-discord-bot --env-file .env cthree-discord-bot
